### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by Naia-love** [zardam/numworks-nofrendo#1]
i do what it's writted (i put less app due to a bug on msys2 with lengt limitation) but it didn't work.
![image](https://user-images.githubusercontent.com/26840567/63505702-49b1a300-c4d4-11e9-8bd7-1236c75c3887.png)

**Comment by Naia-love** [comment]
apparently this is due to a bug, you have to copy epsilon.efl from the build folder to the root.

**Comment by zardam** [comment]
The build system of epsilon has been changed, and I did not update this repository for now. Sorry.
