### ISSUE TITLE
Can't link when compiling to n0110

### ISSUE THREAD

**Issue by EbbDrop** [zardam/numworks-nofrendo#10]
Compiling and linking to the emulator works fine but a error occurs when linking to the n0110.
```
dev/numworks/gcc-arm-none-eabi-9-2019-q4-major/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld:ion/src/device/n0110/flash.ld:187 cannot move location counter backwards (from 0000000020038948 to 0000000020038000)
collect2: error: ld returned 1 exit status
build/rules.mk:45: recipe for target 'output/release/device/n0110/epsilon.elf' failed
make: *** [output/release/device/n0110/epsilon.elf] Error 1
```
It does work when I compile with less apps or without save states. thanks

**Comment by zardam** [comment]
"Cannot move location counter backwards" means that too much RAM is used. One solution is to remove apps, another one is to resize some pre-allocated buffers, see here:
 - https://github.com/numworks/epsilon/blob/13b2deb714c7c125ed07fa0acfe8000ea2acb2c8/apps/calculation/calculation_store.h#L39
 - https://github.com/numworks/epsilon/blob/7123c7c098ab8ec9d8e7c2a963a1de49ed84086d/ion/include/ion/storage.h#L20

**Comment by EbbDrop** [comment]
ok, Thank you
