### ISSUE TITLE
Getting stuck at Manifesting new firmware

### ISSUE THREAD

**Issue by lolocomotive** [zardam/numworks-nofrendo#12]
I tried installing a rom on my numworks 110, I tried with PAL,NTSC and 2 different roms but it always got stuck at the Manifesting new firmware step, where the calculator just turns off and shows a red light on the top.
What did I do wrong?

**Comment by maeldu39** [comment]
log ? debug output ? Are you conscious that if you give 0 thing we can use to know what happened we cant help you ? 
If you can't build the firmware yourself try : https://zardam.github.io/webnofrendo/
And you need to build the firm with an oldder version of epsilon for example version 12. Are you using the n110 app to add nofrendo emu or the firmware change ?

**Comment by lolocomotive** [comment]
I installed it using the web installer and it just got stuck without giving me any error messages. Nevermind because I managed to install nofrendo with omega instead of epsilon.
